// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "USA",
                            Name = "John"
                        },
                        new
                        {
                            Id = 2,
                            Address = "USA",
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 3,
                            Address = "India",
                            Name = "Kumar"
                        },
                        new
                        {
                            Id = 4,
                            Address = "HK",
                            Name = "Bruclee"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Moldives",
                            Name = "Kavari"
                        });
                });

            modelBuilder.Entity("WebApplication2.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebApplication2.Data.OrderItem", b =>
                {
                    b.Property<int>("ProductId");

                    b.Property<int?>("OrderId");

                    b.Property<int>("Price");

                    b.Property<decimal>("ProductCount");

                    b.Property<int?>("ProductId1");

                    b.Property<decimal>("SubTotal");

                    b.HasKey("ProductId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId1");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("WebApplication2.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirt",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shirt",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inner wear",
                            Price = 700m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoe",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "belt",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("WebApplication2.Data.Order", b =>
                {
                    b.HasOne("WebApplication2.Data.Customer", "Customer")
                        .WithMany("Order")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApplication2.Data.OrderItem", b =>
                {
                    b.HasOne("WebApplication2.Data.Order", "Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApplication2.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");
                });
#pragma warning restore 612, 618
        }
    }
}
